#!/bin/sh
#This program will install the Epic Games on your Linux device.

echo "We are starting install process..."
sudo dpkg --add-architecture i386
sudo apt install -q wine python pip python3-tk -y
mkdir -p ~/.cache/epicgames
touch ~/.cache/epicgames/bnk.bnk;
pip install flask requests pywebview[qt] pyqt5
echo "We have installed all dependencies. Please wait while we open your control panel..."
python3 ./panel.py
echo "The installation is now complete."
