#!/bin/sh
# updates the software and launcher.
echo "Updating launcher...";
echo "What is your installation folder name?";
read var;
mv update ..
cd ..
rm -r $var; # removes the directory
echo "Re-installing..."
git clone --quiet https://github.com/JustAnEric/EpicGamesLauncherOnLinux.git # reinstall
echo "Installed newest version.";
cd EpicGamesLauncherOnLinux
rm ./update #removes the update file.
